title: Shubh's Blog
author: ShubhGupta2125
email: shubh.gupta2104@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
    Hi! I am Shubh Gupta, an Incoming Software Developer at Dream11 and your very host.
    This blog contains my cheatsheets and hacking experience! :)
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /blog

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Shubh Gupta
  tagline: Software Developer.
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: shubhgupta 
    github:  ShubhGupta2125
    linkedIn: in/shubh-gupta
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
